---
title: "Community Calls"
---

rOpenSci [Community Calls](https://ropensci.org/commcalls) are Zoom calls held several times a year featuring a panel of speakers on a specific topic with a significant Question & Answer period.
Calls cover a variety of topics, from technical (["A Journey through Arrow in R"](https://ropensci.org/commcalls/jun2023-arrow/))
to community (["Set Up Your Package to Foster a Community"](https://ropensci.org/commcalls/apr2021-pkg-community/)). 
Most topics are in English, but we are introducing Calls in Spanish (["Proyecto Multilingüe"](https://ropensci.org/es/commcalls/nov2023-multilenguaje/)) as well
as in Portugese(["A comunidade R fala português"](https://ropensci.org/commcalls/translation-portuguese/), part of this Pilot)]. 

For general organizing, see our blog post ["How rOpenSci Runs Community Calls"](https://ropensci.org/blog/2021/02/02/ropensci-community-calls/) as well
as our ["Checklist for a Community Call"](https://github.com/ropensci-org/community-calls/blob/master/checklist.md). 

In this chapter we will address the specifics of running a Community Call to 
support first time contributors to open source software.

<!-- TODO: Yani, I would suggest only adding things here which are specific to this 
project. Anything that is a general Community Call organization thing and which
is covered in the above links I think you can either omit, or simply refer to the
above links. No need to 'reinvent the wheel' ;)  -->

## Communication

This communication project connected our community call with the mini-hackathon that followed. Each channel was used to build momentum, share stories, and invite participation. 

We create a event page in our website under Community Calls to share the main information of the event: 

- Date 
- how to join
- Speakers + Bio
- Resources

The event page is shared using our communications channels:

* **Newsletter:** our newsletter have around2500 registered readers. We shared all upcoming community calls in our HQ section and the resources (like video, aricles and slides) after the call.

* **Social Media:** Before the call, we used social media posts to announce the theme and raise awareness. We set the same agenda for all community call: a "Save the date" announcement a month before, a reminder one week before the envent, one day before the event and one hour before the call. 
During the coomunity call, we live-posted under a dedicated hashtag (#traslaton and #rohackathon2025), sharing screenshots, participant quotes, and quick updates to capture the energy of the event. After the call, we posted highlights and linked to the [recap blog](/blog/2025/01/24/coworking-hackathons/), while beginning a countdown to the hackathon.

* **Slack**: ahead of the call, we posted reminders and sparked conversation about the event theme using differents prompts, for example:

- “Do you remember your first time contribution…?”
- “Do you remember the first time you helped someone contribute…?”

These short stories added a personal touch to our communications and inspired people to join the events. 

The "Save the date" announcement is also shared in several Slack workspaces of communities that can be interested on the events, like R-Ladies, R-Devel and LatinR. 

* **Forums**: we also post the Community Call in the event category in several forums related with the topic, like The Carpentries Discuss, Posit Community and Sustain Forum. We share a short summary, the espeakers and the link to the event page in these posts.
