---
title: "Social Media templates"
---

Social media posts on Slack, LinkedIn, and 

## Slack - Maintainers announcement

Hi @channel

Making your first contribution to Open Source can be both empowering and intimidating.
Therefore we’re exited to announce a special series of activities to support first-time contributors to rOpenSci packages! :tada:

In **2025**, we're planning a Community Call and several Coworking sessions/mini hackathons to support first-time contributors.

As part of these sessions, we're looking for rOpenSci package maintainers interested in helping people make their first(ish) contribution to Open Source.
We know that maintaining a package requires a lot of time and effort, and teaching and mentoring someone through their first contribution can also take time. So we're also excited to announce that we have funding to offer participating maintainers a stipend to help offset their time.

See our [blog post](https://ropensci.org/events/coworking-2025-03/)[UPDATE LINK] for more details and how to sign up!

## Slack - Participants

Coworking Mini-Hackathon for First-Time Contributors next week!
:hourglass_flowing_sand: When: Tuesday February 4th 09:00 Australian Western (01:00 UTC)
:grey_exclamation:Join other participants and mentors to make contributions to R package in a fun and supportive environment.
Don't forget to register to participate!
https://ropensci.org/events/coworking-2025-02

## Mastodon/LinkedIn - Maintainers announcement

Looking for Maintainers to Support First-Time Contributors

Making your first contribution to Open Source can be both empowering and intimidating. So we’re exited to announce a special series of activities to support first-time contributors to rOpenSci packages! 🎉

Are you an rOpenSci package maintainer who would like to help someone make their first contribution?

See our blog post for more details and how to sign up (by Nov 24): ropensci.org/blog/2024/10/22/first-time-contributions

# Mastodon/LinkedIn - Maintainers reminder

Reminder!

Making your first contribution to Open Source can be both empowering and intimidating.

Therefore we’re exited to announce a special series of activities to support first-time contributors to rOpenSci packages! 🎉

We're hoping to get enough maintainers registered by this Sunday (Nov 24th) so we can start the ball rolling finding times that work for everyone in 2025.

If you've been thinking about it, here's a mini push to register 😄

ropensci.org/blog/2024/10/22/first-time-contributions

---

Also regarding Supporting First Time Contributions...

If you're interested in participating but don't have an rOpenSci package, or are interested in having people make contributions to your package but don't have time to join the coworking sessions, we also encourage you to register and let us know in the comments. We'll see if we can't come up with some pairings that work for all. Thanks everyone!

ropensci.org/blog/2024/10/22/first-time-contributions

---

We still have some room, so are excited to announce that we can now accept non-rOpenSci package maintainers until December 9th 🎉.

Come help empower and support first-time contributors to R packages through a series of mini-hack-a-thons in 2025.

Details and to sign up: ropensci.org/blog/2024/10/22/first-time-contributions


## Mastodon/LinkedIn - Participant 

Coworking Mini-Hackathon for First-Time Contributors 🎉

Curious or excited about contributing to Open Source Software? Would you like some support to get started?
If any of the above, our upcoming coworking mini-hackathons are for you!

Feb 4th 2025 1-3 UTC and March 4th 2025 13-15 UTC

Join us and contribute to R packages while package maintainers and other mentors are available 'live' to answer questions and give guidance.

See our blog post for more details: ropensci.org/blog/2025/01/24/coworking-hackathons
