on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Build Site

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: quarto-dev/quarto-actions/setup@v2
    
      - name: Render Book project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Publish HTML book
          uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website/_book # The folder the action should deploy.
